name: agroguard

services:
  flask:
    hostname: flask
    depends_on:
      - mysql-db
    build: ./meadow-be
    ports:
      - "5000:5000"
    command: python app.py

  mysql-db:
    hostname: mysql-db
    image: m.daocloud.io/docker.io/library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: meadow123
      MYSQL_DATABASE: meadow_test
    ports:
      - "5010:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts/meadow_test-2025_03_21_18_30_21-dump.sql:/docker-entrypoint-initdb.d/01_dump.sql:Z
      - ./migrations/rename_d_health_to_d_plantcare.sql:/docker-entrypoint-initdb.d/02_rename_d_health_to_d_plantcare.sql:Z
      - ./migrations/rename_e_breed_to_e_cultivation.sql:/docker-entrypoint-initdb.d/03_rename_e_breed_to_e_cultivation.sql:Z
  vue:
    hostname: vue
    depends_on:
      - flask
    build: ./meadow-fe
    ports:
      - "5020:80"

volumes:
  mysql-data:

