name: agroguard

services:
  flask:
    hostname: flask
    depends_on:
      - mysql-db
    build: ./sheep-be
    ports:
      - "5000:5000"
    command: python app.py

  mysql-db:
    hostname: mysql-db
    image: m.daocloud.io/docker.io/library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sheep123
      MYSQL_DATABASE: sheep_test
    ports:
      - "5010:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d:Z
  vue:
    hostname: vue
    depends_on:
      - flask
    build: ./sheep-fe
    ports:
      - "5020:80"

volumes:
  mysql-data:

